version: '3'

services:
  postgresql:
    image: postgres:10
    restart: always
    container_name: postgresql
    volumes:
        - db_data:/var/lib/postgresql/data
        - .:/test_capistrano
    ports:
        - "5432:5432"
    environment:
        POSTGRES_DB: test_capistrano_development
        POSTGRES_USER: root
        POSTGRES_PASSWORD: root

  test_capistrano:
    build: .
    container_name: test_capistrano
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/test_capistrano
      - web_rubygems:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - postgresql
    # Debug binding.pry trên Docker
    tty: true 
    stdin_open: true

volumes:
  db_data:
  web_rubygems: